
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package proyecto1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int tkGraficaLineas = 13;
  public static final int tkPuntajeEspecifico = 16;
  public static final int tkCadena = 29;
  public static final int tkGraficaBarras = 6;
  public static final int tkId = 28;
  public static final int tkNumero = 27;
  public static final int tkTitulo = 7;
  public static final int tkDolar = 24;
  public static final int tkIgual = 18;
  public static final int tkPuntoComa = 23;
  public static final int tkDosPuntos = 19;
  public static final int tkLlaveC = 31;
  public static final int tkLlaveA = 30;
  public static final int tkGenerarReporteEstadistico = 3;
  public static final int EOF = 0;
  public static final int tkValores = 9;
  public static final int tkComa = 22;
  public static final int tkCorcheteC = 21;
  public static final int tkEjeX = 8;
  public static final int tkDefinirGlobales = 2;
  public static final int error = 1;
  public static final int tkCorcheteA = 20;
  public static final int tkCompare = 17;
  public static final int tkTituloY = 11;
  public static final int tkTituloX = 10;
  public static final int tkPuntajeGeneral = 15;
  public static final int tkGraficaPie = 12;
  public static final int tkDouble = 5;
  public static final int tkParentesisC = 26;
  public static final int tkString = 4;
  public static final int tkParentesisA = 25;
  public static final int tkArchivo = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tkDefinirGlobales",
  "tkGenerarReporteEstadistico",
  "tkString",
  "tkDouble",
  "tkGraficaBarras",
  "tkTitulo",
  "tkEjeX",
  "tkValores",
  "tkTituloX",
  "tkTituloY",
  "tkGraficaPie",
  "tkGraficaLineas",
  "tkArchivo",
  "tkPuntajeGeneral",
  "tkPuntajeEspecifico",
  "tkCompare",
  "tkIgual",
  "tkDosPuntos",
  "tkCorcheteA",
  "tkCorcheteC",
  "tkComa",
  "tkPuntoComa",
  "tkDolar",
  "tkParentesisA",
  "tkParentesisC",
  "tkNumero",
  "tkId",
  "tkCadena",
  "tkLlaveA",
  "tkLlaveC"
  };
}

