
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package proyecto1;

/** CUP generated class containing symbol constants. */
public class symJS {
  /* terminals */
  public static final int tkPorcentaje = 36;
  public static final int tkLog = 15;
  public static final int tkFalse = 20;
  public static final int tkDivision = 35;
  public static final int tkConsole = 14;
  public static final int tkLet = 4;
  public static final int tkOr = 40;
  public static final int tkNumero = 44;
  public static final int tkCase = 12;
  public static final int tkConst = 5;
  public static final int tkIf = 6;
  public static final int tkId = 45;
  public static final int tkVar = 3;
  public static final int tkDosPuntos = 23;
  public static final int tkCorcheteC = 25;
  public static final int tkMas = 32;
  public static final int tkCorcheteA = 24;
  public static final int tkIgual = 22;
  public static final int EOF = 0;
  public static final int tkPor = 34;
  public static final int tkCaracter = 47;
  public static final int tkLlaveC = 31;
  public static final int tkLlaveA = 30;
  public static final int error = 1;
  public static final int tkClass = 2;
  public static final int tkTrue = 19;
  public static final int tkComa = 26;
  public static final int tkFor = 8;
  public static final int tkNull = 18;
  public static final int tkAnd = 39;
  public static final int tkNot = 38;
  public static final int tkReturn = 21;
  public static final int tkMenos = 33;
  public static final int tkMenor = 42;
  public static final int tkBreak = 16;
  public static final int tkElse = 7;
  public static final int tkRequire = 17;
  public static final int tkCadena = 46;
  public static final int tkParentesisC = 29;
  public static final int tkMayor = 41;
  public static final int tkPotencia = 37;
  public static final int tkParentesisA = 28;
  public static final int tkDo = 10;
  public static final int tkSwitch = 11;
  public static final int tkPunto = 43;
  public static final int tkWhile = 9;
  public static final int tkPuntoComa = 27;
  public static final int tkDefault = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tkClass",
  "tkVar",
  "tkLet",
  "tkConst",
  "tkIf",
  "tkElse",
  "tkFor",
  "tkWhile",
  "tkDo",
  "tkSwitch",
  "tkCase",
  "tkDefault",
  "tkConsole",
  "tkLog",
  "tkBreak",
  "tkRequire",
  "tkNull",
  "tkTrue",
  "tkFalse",
  "tkReturn",
  "tkIgual",
  "tkDosPuntos",
  "tkCorcheteA",
  "tkCorcheteC",
  "tkComa",
  "tkPuntoComa",
  "tkParentesisA",
  "tkParentesisC",
  "tkLlaveA",
  "tkLlaveC",
  "tkMas",
  "tkMenos",
  "tkPor",
  "tkDivision",
  "tkPorcentaje",
  "tkPotencia",
  "tkNot",
  "tkAnd",
  "tkOr",
  "tkMayor",
  "tkMenor",
  "tkPunto",
  "tkNumero",
  "tkId",
  "tkCadena",
  "tkCaracter"
  };
}

